name: Set up OCaml
description: Set up an OCaml and opam environment and add to PATH
author: Anil Madhavapeddy
branding:
  icon: package
  color: orange
inputs:
  ocaml-version:
    description: Version of the OCaml compiler to initialise
    default: 4.08.1
  opam-repository:
    description: URL of the repository to fetch packages from
    default: ""
  github-token:
    required: false
    default: ${{ github.token }}
runs:
  using: node16
  main: dist/index.js
