name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.08.1
          - 4.05.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install npm packages
        run: yarn --frozen-lockfile

      - name: Check type
        run: yarn typecheck

      - name: Run build
        run: yarn build

      - name: Correct vercel/ncc crlf output
        run: sed -i 's/\x0D$//' ./dist/index.js

      - name: Ensure dist directory is up-to-date
        if: runner.os == 'Linux'
        shell: bash
        run: |
          if [ "$(git status dist --porcelain | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ./
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam depext yaml --install --verbose --yes

      - name: Check formatting
        run: yarn fmt:check
        if: always()

      - name: Check lint
        run: yarn lint
        if: always()
