name: Builds, tests & co

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

permissions: read-all

jobs:
  hygiene:
    name: Hygiene

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Set-up Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: latest

      - run: corepack enable

      - run: yarn install --immutable

      - if: always()
        run: yarn lint

      - if: always()
        run: yarn typecheck

      - name: Ensure dist directory is up-to-date
        if: always()
        run: yarn build && git diff --exit-code --ignore-cr-at-eol

  test:
    name: Test

    needs: hygiene

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - "5.2"
        include:
          - os: ubuntu-latest
            ocaml-compiler: ocaml-variants.5.2.0+options,ocaml-option-flambda

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ./
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam install uri
